### ISSUE TITLE
Broken file fragments.tsv.gz

### ISSUE THREAD

**Issue by wangjk321** [hyndmank/snATAC_Hyndman#1]
Hello, thank you for your wonderful paper. 

I'm trying to use your code and data. But when I checked the snATAC-seq data https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE181557,  I found the file such as `GSM5506058_77_fragments.tsv.gz` is not usable. The file only have ~1500 lines, and the last line is incomplete:

```
chr1	3185272	3185420	CACGTTCTCTCGTGAA-1	2
chr1	3185292	3185490	CAGTATGAGTCGAGCA-1	1
chr1	3185347			
``` 

When I delete the last line, and run 
```
frags.fko <- CreateFragmentObject(
  path = "GSM5506059_76_fragments.tsv.gz",
  cells = rownames(metadata.mko))
``` 
An error occured: `Not all cells requested could be found in the fragment file.`

So, Can you share me the correct fragments file of GSE181557 ?

**Comment by hyndmank** [comment]
Let me contact GEO and see what I can do. Thanks for letting me know.  I'll let you know when they are fixed.

**Comment by hyndmank** [comment]
Files have been uploaded plus I gave the h5 and the tbi file too.

**Comment by wangjk321** [comment]
Thank you so much!, You saved my life.
